include: "rules/common.smk"


##### Target rules #####


rule all:
    input:
        "results/annotated/all.vcf.gz",
        "results/qc/multiqc.html",
        "results/plots/depths.svg",
        "results/plots/allele-freqs.svg",

        expand("results/recal/merged/{sample}.bam.bai", sample=samples.index) # merged (all units) bam files


##### Modules #####


include: "rules/ref.smk"
include: "rules/mapping.smk"
include: "rules/calling.smk"
include: "rules/filtering.smk"
include: "rules/stats.smk"
include: "rules/qc.smk"
include: "rules/annotation.smk"
